/* Cyber Case: shared task data for all three stations. No em dashes anywhere in the copy. */
const TASKS = {

  fakenews: {
    key: "fakenews",
    number: 1,
    title: "Spot Fake News",
    shortTitle: "Fake News",
    subtitle: "REAL vs. FAKE: verify before you trust it",
    verdictLabels: ["REAL", "FAKE"],
    itemKindLabel: "ITEM",
    itemsSectionTitle: "The Articles and Posts",
    definitionTerm: "fake news (noun)",
    definitionBody: "information presented as a real news story that is false, misleading, or missing important context. It is designed to get clicks, provoke outrage, or spread a rumor rather than inform.",
    howItWorks: [
      { icon: "🔍", t: "Check the Source", d: "Is it a real, credible outlet? Is there a named author and a date?" },
      { icon: "🧩", t: "Check the Context", d: "Does the full story or quote match the headline, or has it been clipped?" },
      { icon: "😱", t: "Check the Tone", d: "Is it calm and specific, or urgent, vague, and pushing you to share fast?" },
    ],
    instructions: "Work with your partner to read each article or post below. Decide whether it is REAL or FAKE, and write down the specific clues in the evidence box: checking the source, the date, the context, and the tone. When you are done with all items, submit to see your score and a summary you can show a judge.",
    items: [
      {
        kind: "article",
        fields: [["Outlet", "TruthAlertDaily.co"], ["Author", "Not listed"], ["Date", "Not listed"]],
        body: [
          "LOCAL WATER SUPPLY CONTAINS MICROCHIPS, SCIENTIST WARNS",
          "A concerned citizen claims tiny microchips have been found in the city's tap water, allegedly placed there to track residents. \"Everyone needs to know the truth,\" the article states, without naming the scientist, the lab that supposedly tested the water, or any way to verify the claim.",
          "Share this before it gets taken down!",
        ],
        verdict: "FAKE",
        why: "No named source, no evidence, no author or date, and a request to share before it gets taken down. That is a classic pressure tactic used to spread unverified claims quickly.",
      },
      {
        kind: "article",
        fields: [["Outlet", "Port Herald"], ["Author", "Maria Suweni, Staff Reporter"], ["Date", "July 29, 2026"]],
        body: [
          "CITY ANNOUNCES NEW RECYCLING PROGRAM STARTING SEPTEMBER",
          "The City Council voted 6-1 on Tuesday to launch a curbside recycling program beginning September 1. Residents will receive color coded bins by mid August.",
          "\"This has been years in the planning,\" said Public Works Director Tomas Aleku. \"We're grateful residents have been patient while we got the logistics right.\" Full details are posted on the city's official website.",
        ],
        verdict: "REAL",
        why: "Named reporter and outlet, specific date, a named official with a direct quote, a verifiable vote count, and a way to check further on the city's official site.",
      },
      {
        kind: "article",
        fields: [["Outlet", "healthmiraclehub.net"], ["Author", "Not listed"], ["Date", "Not listed"]],
        body: [
          "DOCTORS HATE HIM: LOCAL MAN DISCOVERS ONE WEIRD TRICK THAT CURES EVERYTHING",
          "A local man says he cured his chronic pain, boosted his energy, and lost 20kg using a single household ingredient doctors don't want you to know about. Click below to find out what it is before this article gets banned.",
        ],
        verdict: "FAKE",
        why: "Sensational clickbait headline, no named person or doctor, vague miracle claims, and a click bait link to a hidden answer. That is the hallmark structure of an ad or scam dressed up as an article.",
      },
      {
        kind: "article",
        fields: [["Outlet", "National Weather Service"], ["Author", "Official Advisory"], ["Date", "August 1, 2026"]],
        body: [
          "HEAVY RAIN ADVISORY ISSUED FOR THE WEEKEND",
          "The National Weather Service has issued a heavy rain advisory in effect from Saturday 6:00 AM through Sunday 11:59 PM. Residents in low lying areas should prepare for possible localized flooding.",
          "Rainfall totals of 80 to 120mm are expected. Avoid unnecessary travel during peak hours if possible.",
        ],
        verdict: "REAL",
        why: "Official government source, a specific and checkable timeframe and rainfall figures, and practical, not alarmist, guidance. That is consistent with how real advisories are worded.",
      },
      {
        kind: "social",
        fields: [["Handle", "@NewsFlash_Now"], ["Platform", "X (unverified account)"], ["Posted", "2 minutes ago"]],
        body: [
          "BREAKING!! Coral Bay Bank has FROZEN all customer accounts effective immediately!! my cousin works their and says its true they just wont say it publicly yet RT before this gets deleted",
        ],
        verdict: "FAKE",
        why: "Unverified account, no link to an official source, vague hearsay about a cousin who supposedly works there, excessive urgency, and an explicit push to reshare before it gets deleted. All of that points to an unverified rumor.",
      },
      {
        kind: "article",
        fields: [["Outlet", "Port Herald"], ["Author", "Daniel Okoro, Education Desk"], ["Date", "July 22, 2026"]],
        body: [
          "LOCAL SCHOOL WINS NATIONAL SCIENCE COMPETITION",
          "Students from Riverside Secondary School took first place at the National Youth Science Fair for a water filtration project designed for rural communities.",
          "\"The team spent six months testing prototypes after school,\" said Principal Grace Namu. \"We're incredibly proud of what they built.\" The team will represent the region at the regional finals in October.",
        ],
        verdict: "REAL",
        why: "Named school, a named principal with a direct quote, specific and checkable competition and project details, and a credible outlet with a named reporter.",
      },
      {
        kind: "article",
        fields: [["Outlet", "CityBuzzToday.com"], ["Author", "Not listed"], ["Date", "August 2, 2026"]],
        body: [
          "MAYOR: \"WE DON'T CARE ABOUT FLOODING VICTIMS\"",
          "In a clip circulating online, the mayor is quoted saying \"we don't care about flooding victims\" during a budget meeting, sparking outrage online.",
          "Editor's note added after this posted: the full recording shows the mayor's complete sentence was, \"If we don't act now, it will look like we don't care about flooding victims, and that's why this funding has to pass today.\" The clip removed the first half of the sentence.",
        ],
        verdict: "FAKE",
        why: "A quote taken out of context. The full recording reverses the meaning entirely, which is why checking the original source and context matters, not just the headline.",
      },
      {
        kind: "article",
        fields: [["Outlet", "Business Wire Desk"], ["Author", "Staff Report"], ["Date", "July 30, 2026"]],
        body: [
          "TECHCORE LTD REPORTS QUARTERLY EARNINGS, MEETS ANALYST EXPECTATIONS",
          "TechCore Ltd reported quarterly revenue of $412 million, in line with analyst forecasts of $405 to $420 million. The company's CEO cited steady demand in its cloud services division.",
          "Shares were largely unchanged in after hours trading. The company will hold its investor call Thursday at 9:00 AM.",
        ],
        verdict: "REAL",
        why: "Specific, checkable figures that are consistent with analyst forecasts rather than a sensational surprise, a calm and neutral tone, and a named upcoming event. That is typical of routine financial reporting.",
      },
    ],
  },

  aiimages: {
    key: "aiimages",
    number: 2,
    title: "Detect AI Generated Images",
    shortTitle: "AI Images",
    subtitle: "REAL vs. AI: train your eye",
    verdictLabels: ["REAL", "AI"],
    itemKindLabel: "IMAGE",
    itemsSectionTitle: "The Images",
    definitionTerm: "AI generated image (noun)",
    definitionBody: "a picture created or altered by artificial intelligence rather than captured by a camera. Some are obvious, like a UFO floating in the sky, and some are almost perfect, hiding just one small flaw.",
    howItWorks: [
      { icon: "🖐️", t: "Hands and Faces", d: "Count the fingers. Check if faces or features look slightly warped or too smooth." },
      { icon: "💡", t: "Light and Shadow", d: "Do shadows point the same direction as the light source? Does anything glow oddly?" },
      { icon: "🧱", t: "Patterns and Backgrounds", d: "Look for repeating tiles, melting edges, or objects that do not quite connect." },
    ],
    instructions: "Work with your partner to examine each image below. Zoom in if you can. Decide whether it is a REAL photograph or an AI GENERATED image, and write down the specific clue in the evidence box: a hand, a shadow, a background detail, anything that does not add up. Some fakes are obvious, some are subtle, so read carefully. When you are done with all images, submit to see your score and a summary you can show a judge.",
    items: [
      {
        kind: "image",
        src: "images/JerusalemReal.jpg",
        verdict: "REAL",
        why: "A genuine photograph. Consistent lighting across the whole skyline, natural cloud texture, and fine architectural detail on the buildings and dome all hold up under a closer look.",
      },
      {
        kind: "image",
        src: "images/GreatWallAI.jpg",
        verdict: "AI",
        why: "Look for the flying saucer near the mountains. It is a composited object with sharper edges and different lighting than the hazy landscape around it, a dead giveaway it was not part of the original scene.",
      },
      {
        kind: "image",
        src: "images/vegasReal.jpg",
        verdict: "REAL",
        why: "A real long exposure night photo. The light trails from moving traffic are a genuine slow shutter speed camera technique, and the signage (Bally's, Jersey Boys, the street sign) is crisp and fully legible, which AI generators still struggle to render correctly.",
      },
      {
        kind: "image",
        src: "images/TajmahalReal.jpg",
        verdict: "REAL",
        why: "A real, candid daytime photo. The crowd is dense and imperfectly posed, the lighting is ordinary midday sun rather than an idealized sunset, and individual faces and clothing hold up under a closer look, all signs of an unstaged photograph rather than a generated one.",
      },
      {
        kind: "image",
        src: "images/GezaREAL.jpg",
        verdict: "REAL",
        why: "A real photograph. Ordinary tourists at natural scale, authentic stone block texture and weathering, and nothing structurally impossible about the pyramid's geometry.",
      },
      {
        kind: "image",
        src: "images/MayanAI.jpeg",
        verdict: "AI",
        why: "The green alien figure and the floating low poly pyramid and tree are obviously composited elements in a completely different visual style from the photo realistic ruins. They simply do not belong in the scene.",
      },
      {
        kind: "image",
        src: "images/PeopleAI.jpeg",
        verdict: "AI",
        why: "Look closely at the standing man's hand on the right: his fingers are missing or malformed. Hands are one of the most common tells in AI generated images, even when the rest of the scene looks completely normal.",
      },
      {
        kind: "image",
        src: "images/ManhattanAI.jpg",
        verdict: "AI",
        why: "The buildings and bridges warp and repeat in ways that do not make architectural sense. Blocks melt into each other, bridges do not connect logically, and the water texture is inconsistent: classic AI generated cityscape artifacts.",
      },
    ],
  },

  phishing: {
    key: "phishing",
    number: 3,
    title: "Identify Phishing Emails",
    shortTitle: "Phishing",
    subtitle: "LEGITIMATE vs. PHISHING: spot the scam",
    verdictLabels: ["LEGITIMATE", "PHISHING"],
    itemKindLabel: "EMAIL",
    itemsSectionTitle: "The Emails",
    definitionTerm: "phishing (noun)",
    definitionBody: "when a scammer sends a fake message, pretending to be a bank, a company, or even someone you know, to trick you into clicking a bad link or handing over passwords, card numbers, or personal info.",
    howItWorks: [
      { icon: "🎣", t: "The Bait", d: "A message that looks real: urgent, exciting, or scary, made to grab your attention." },
      { icon: "🔗", t: "The Hook", d: "A link or attachment that leads to a fake site or steals your info when clicked." },
      { icon: "⚠️", t: "The Catch", d: "Once you enter details, the scammer can access your account, money, or identity." },
    ],
    instructions: "Work with your partner to review each email below. Decide whether it is LEGITIMATE or PHISHING, and write down every clue in the evidence box: sender address, links, spelling and grammar, urgency, and any request for personal info. When you are done with all emails, submit to see your score and a summary you can show a judge.",
    items: [
      {
        kind: "email",
        fields: [["From", "NetraBank Security <alerts@netra-bank-secure.com>"], ["Subject", "URGENT: Your Account Will Be Suspended in 24 Hours"], ["Date", "Mon, 3 Aug 2026, 11:42 PM"]],
        body: [
          "Dear Customer,",
          "We detected unusual activity on you're account. For you're protection, we have temporarily limited some features.",
          "You must verify you're identity immediately or you're account will be suspended within 24 hours.",
          "Click here to confirm your details: http://netra-bank-secure.com.verify-login.info/confirm",
          "You will need to enter your username, password, and card PIN to restore full access.",
          "NetraBank Security Team",
        ],
        verdict: "PHISHING",
        why: "A lookalike domain, repeated grammar errors like you're instead of your, a generic greeting, manufactured urgency, and a direct request for your password and PIN.",
      },
      {
        kind: "email",
        fields: [["From", "CloudDrive Solutions <billing@clouddrivesolutions.com>"], ["Subject", "Your storage is almost full (90% used)"], ["Date", "Tue, 28 Jul 2026, 9:14 AM"]],
        body: [
          "Hi J. Torres,",
          "Your CloudDrive storage is currently at 90% capacity. Once you reach 100%, new files won't be able to sync.",
          "You can free up space by deleting old files, or review upgrade options anytime from your account dashboard at clouddrivesolutions.com/account.",
          "We won't ask you to confirm your password by email. If you ever get a message asking for that, please report it to us.",
          "The CloudDrive Solutions Team",
        ],
        verdict: "LEGITIMATE",
        why: "The sender domain matches the link given, it addresses you by name, there is no urgency or credential request, and it proactively tells you they will never ask for your password.",
      },
      {
        kind: "email",
        fields: [["From", "International Prize Bureau <claims@prizewinner-notify.net>"], ["Subject", "CONGRATULATIONS!!! You Have Won $850,000"], ["Date", "Sun, 2 Aug 2026, 3:07 AM"]],
        body: [
          "Dear Winner,",
          "We are pleased to inform you that your email adress has been selected as a winner of $850,000 USD in our International Online Sweepstakes.",
          "To claim you're prize, kindly reply with your full name, home address, date of birth, and a copy of your ID.",
          "A small processing fee of $150 is required to release the funds. Payment must be recieved within 24 hours or your prize will be forfeited.",
          "Ms. Angela Reyes, Claims Officer",
        ],
        verdict: "PHISHING",
        why: "An unsolicited too good to be true prize, spelling errors, a suspicious domain, requests for ID and personal details, and an upfront processing fee. That is a classic scam pretext.",
      },
      {
        kind: "email",
        fields: [["From", "Priya Nandan, HR <priya.nandan@brightoffice.co>"], ["Subject", "Team meeting moved to 3pm Thursday"], ["Date", "Wed, 30 Jul 2026, 2:20 PM"]],
        body: [
          "Hi all,",
          "Quick note: Thursday's team meeting has been moved from 10am to 3pm in Conference Room B, since a few people have a scheduling conflict in the morning.",
          "Same agenda: Q3 planning and the new onboarding checklist. Let me know if 3pm doesn't work for you.",
          "Priya",
        ],
        verdict: "LEGITIMATE",
        why: "A consistent sender name and domain, ordinary low stakes workplace content, no links or credential requests, and a plausible specific reason for the change.",
      },
      {
        kind: "email",
        fields: [["From", "IT Helpdesk <it-support@company-helpdesk-secure.com>"], ["Subject", "Password Expiry Notice: Action Required Within 2 Hours"], ["Date", "Fri, 1 Aug 2026, 4:58 PM"]],
        body: [
          "Dear Employee,",
          "Our records indicate that your network password will expire in 2 hours. To avoid being locked out of your account, you must reset it immediately.",
          "Reset your password now: http://company-helpdesk-secure.com/reset?id=88213",
          "Please enter your current password and new password on the next screen to complete verification.",
          "This is an automated message from IT Helpdesk. Do not reply.",
        ],
        verdict: "PHISHING",
        why: "An outside domain impersonating internal IT, a tight two hour threat, and a request for your CURRENT password. Real resets never ask for your old password by email.",
      },
      {
        kind: "email",
        fields: [["From", "Billing <billing@brightofficesupplies.com>"], ["Subject", "Invoice #4471 for July order"], ["Date", "Thu, 24 Jul 2026, 10:05 AM"]],
        body: [
          "Hello,",
          "Attached is invoice #4471 for your July order of office supplies (total: $312.40), due within 30 days.",
          "You can view or download the invoice anytime from your account at brightofficesupplies.com/orders.",
          "If you have any questions about this invoice, just reply to this email or call our accounts line at (07) 555-0148.",
          "Bright Office Supplies, Accounts Team",
        ],
        verdict: "LEGITIMATE",
        why: "The sender domain matches the vendor and link, it has ordinary invoice content with no credential request, and it offers a real phone number for questions.",
      },
      {
        kind: "email",
        fields: [["From", "Swift Express Tracking <delivery@swift-express-tracking.info>"], ["Subject", "Delivery Failed - Action Required Immidiately"], ["Date", "Sat, 1 Aug 2026, 6:33 AM"]],
        body: [
          "Dear Customer,",
          "We attempted to deliver your parcel but it could not be recieved due to an incomplete address.",
          "To reschedule delivery, please click below and confirm your address and pay a small redelivery fee of $2.99 using your card details:",
          "http://swift-express-tracking.info/redeliver?track=SX88214",
          "Swift Express Tracking Support",
        ],
        verdict: "PHISHING",
        why: "A suspicious domain, spelling errors like Immidiately and recieved, and a request for card details to pay a trivial redelivery fee. That is a common phishing pretext.",
      },
      {
        kind: "email",
        fields: [["From", "StreamFlix Receipts <receipts@streamflix.com>"], ["Subject", "Your receipt for August: $12.99"], ["Date", "Mon, 3 Aug 2026, 7:00 AM"]],
        body: [
          "Hi there,",
          "This confirms your StreamFlix subscription payment of $12.99 was processed on August 1, 2026.",
          "Plan: Standard | Next billing date: September 1, 2026",
          "No action is needed. You can view your billing history anytime by logging in directly at streamflix.com.",
          "StreamFlix",
        ],
        verdict: "LEGITIMATE",
        why: "The sender domain matches the real service, it is purely informational with no action required, and it directs you to log in directly rather than through an embedded link.",
      },
    ],
  },
};
